### ISSUE TITLE
회원가입 & 로그인 파라미터 검증 및 에러 헨들링 로직

### ISSUE THREAD

**Issue by Unperknown** [Junyeong-Market/Eliverd-API#16]
아래 요청에 대해서 파라미터 검증과 에러 헨들링과 관련해서 협의해야 할 사항이 있습니다.
- `POST /account/user` => 사용자 회원가입
- `POST /account/session` => 사용자 로그인(세션 생성)

애플리케이션 View 단에서 사용자가 회원가입이나 로그인에 실패했을 때 현재 아래와 같이 에러 메시지를 띄우게 할 예정입니다.

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-18 at 08 29 46](https://user-images.githubusercontent.com/37747694/84965379-bd9af700-b149-11ea-8bfe-8afff74c8c05.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-06-17 at 20 55 20](https://user-images.githubusercontent.com/37747694/84965386-c095e780-b149-11ea-81c2-de25d867d111.png)

파라미터 검증과 관련해서는 애플리케이션 내(프론트엔드 쪽)에서 잘못된 데이터를 보내지 않도록 할 수도 있고 서버에서 응답할 때 어느 파라미터가 잘못되었는지 응답을 보내는 두 가지 방법이 있는데 어느 쪽으로 하면 좋을지 코멘트를 남겨주세요!

만약 서버 단에서 파라미터 검증과 에러 헨들링을 한다면 로그인을 할 때 에러 응답이 몇 가지 정도 있을지도 같이 코멘트 남겼으면 좋겠습니다.

**Comment by Unperknown** [comment]
이 코멘트는 현재 회원가입 및 로그인 UI입니다.

## 회원가입
![Simulator Screen Shot - iPhone 11 Pro - 2020-06-17 at 20 55 22](https://user-images.githubusercontent.com/37747694/84965592-474ac480-b14a-11ea-9733-f64bcb812e97.png)

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-17 at 20 56 07](https://user-images.githubusercontent.com/37747694/84965597-4b76e200-b14a-11ea-838e-e9d29f84f253.png)

## 로그인

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-17 at 20 55 17](https://user-images.githubusercontent.com/37747694/84965616-55004a00-b14a-11ea-9695-0d6a4c4d8cbd.png)

**Comment by startergate** [comment]
이름: 128자 이내, 영어 한글로만 구성
닉네임: 50자 이내, unique, 영어 한글 숫자로만 구성
아이디: 50자 이내, unique, 영어 숫자로만 구성
비밀번호: 256자 이내, 영어 숫자 특수문자로만 구성

**Comment by startergate** [comment]
response:
```json
{
    "realname": "string",
    "nickname": "string",
    "id": "string",
    "password": "string"
}
```
에러는 문장으로 표시합니다.
이미 존재하는 데이터: "user with this {data_name} already exists."
형식 문제: "Ensure this field has {data_error}".
에러가 없으면 검증된 데이터를 반환합니다.
```json
{
    "user_id": "string",
    "password": "string",
    "realname": "사용자",
    "nickname": "string",
    "is_seller": false
}
```

**Comment by startergate** [comment]
path는 `/account/user/validate`를 사용할 계획입니다.

**Comment by startergate** [comment]
@Unperknown @Parkjonghyo
