### ISSUE TITLE
사업장 등록 관련 협의할 사항

### ISSUE THREAD

**Issue by Unperknown** [Junyeong-Market/Eliverd-API#17]
사업장 등록 로직과 관련해서 협의할 사항이 있습니다.

현재 애플리케이션 내에서 사업장은 Store 엔티티로 다음과 같은 필드가 있습니다.
- 이름(사업장 이름, UQ여야 할 것으로 예상)
- 설명(사업장 설명)
- 사업자(사업장 등록자)
- 사업자등록번호(UQ여야 할 것으로 예상)
- 위치(위도+경도)

첫번째로, 사업장 등록 시 파라미터에 대해서 도메인 충족 여부 및 중복 검사 등으로 검증하는 과정이 필요합니다. 이는 #16 에서 한 과정을 반복하면 될 것 같습니다.

그런데 추가로 현재 사업자를 여러 명 등록하는 조건을 구현하는 데 까다로운 부분이 있어서 아래의 두 가지 경우 중 하나를 선택해서 해야 합니다.
- 애플리케이션에서 (is_seller가 true인) **전체 사업장 유저를 검색**해서 찾는 기능을 추가하여 등록하도록 함
> 예상 기능: 사업자가 다른 사업자 검색 => 사업장 등록 시 선택해서 등록
> 사업장 유저를 검색할 수 있는 요청이 필요함, 구현이 다소 까다로울 것으로 예상
- 검색 기능을 빼고 간단하게 프로토타입 상으로만 사업자를 한 명만 등록하게 제한하여(등록 요청 시 사업자를 로그인한 유저 정보로 넣어서) 사업자가 수동으로 등록하게 함
> 이 경우, 구현이 간단하지만 사업자를 여러 명으로 설계한 의미가 없어짐

**Comment by startergate** [comment]
`POST /account/user/search/{name}?is_seller=true`
