### ISSUE TITLE
사업자 데이터 추출 형태 수정하기

### ISSUE THREAD

**Issue by Unperknown** [Junyeong-Market/Eliverd-API#33]
현재 사업장과 관련한 API의 모든 응답에서 사업자(registerer)를 PK의 리스트 형태로 응답하는 것으로 구현되어 있는데 이를 사업자 데이터 자체(튜플)로 반환했으면 좋겠습니다. 수정해야 할 부분은 아래와 같습니다.
- `POST /store`의 응답 JSON 포맷에서 registerers의 value를 사업자(User) 리스트로 변환
- `GET /store/:id`의 응답 JSON 포맷에서 registerer의 value를 사업자(User) 리스트로 변환

**Comment by startergate** [comment]
/store/{id} 는 수정되어 있습니다

**Comment by startergate** [comment]
수정 완료

**Comment by startergate** [comment]
적용 완료
