### ISSUE TITLE
Eliverd 소비자용 애플리케이션에 필요한 API 기능 정의

### ISSUE THREAD

**Issue by Unperknown** [Junyeong-Market/Eliverd-API#36]
Eliverd 소비자용 애플리케이션을 구현하는 데 서버 API를 추가적으로 구현해야 할 부분이 있을 것입니다. 다음은 소비자용 애플리케이션에서 이루어지는 기능을 정의한 것입니다. 이 이슈에서 아래 기능에 따라 API를 어떻게 구성해야 할지 코멘트를 남겨주세요😶

- 상품(Product)을 카테고리에 따라 검색함 => 지도에 재고와 그에 따른 '남은 재고 수', '상점'을 볼 수 있음
- 상품을 주문하고 결제함(장바구니[로컬로 처리], 주문 폼 작성[+ 배송 주소 지정], 결제 요청 등)
- 주문 내역을 조회함
- 설정 페이지에서 카테고리 필터를 수정함
- 애플리케이션 하단을 스크롤하여 상품 소개 Bottom Sheet를 봄
- 검색 후 지도의 마커를 클릭하여 상품 상세 소개를 조회함(상점의 간략한 정보, 카테고리로 필터링된 재고 목록)
- 설정 페이지에서 사용자 정보를 수정/탈퇴함

**Comment by startergate** [comment]
남은 재고 수는 최대 주문 가능 수량으로 표시해도 될 것 같아요 @Unperknown

**Comment by startergate** [comment]
이 중 백엔드에서는 상품 검색, 주문 결제, 주문 내역 조회만 API로 구현될 예정입니다. 나머지는 이미 구현되어 있거나, 백엔드가 필요 없는 기능들입니다.

**Comment by startergate** [comment]
#38 #39 #37 #35 여기서 구현됩니다.
