### ISSUE TITLE
상품(Product) 카테고리 정보 추가하기

### ISSUE THREAD

**Issue by Unperknown** [Junyeong-Market/Eliverd-API#41]
앞으로 소비자용 Eliverd 애플리케이션과 통합하기 위해서 Product 엔티티에 카테고리 칼럼을 추가하고 이에 접근하는 모든 API 엔드포인트를 알맞게 수정해야 합니다. 아래는 해당하는 엔드포인트입니다.
- `GET /store/:id/stocks`
- `POST /store/:id/stock`(재고 추가 시에)
- `GET /product/:ian`

**Comment by Unperknown** [comment]
추가로 Eliverd에서 처리되는 모든 상품의 카테고리는 서버에서 정한 열거형 타입으로 관리할 수 있도록 하는 것이 좋을 것 깉습니다.

**Comment by startergate** [comment]
모델 적용 완료

**Comment by startergate** [comment]
반영이 완료되어 있습니다. 서버에는 곧 올라갑니다
