### ISSUE TITLE
API 인증 기능 점검 요청

### ISSUE THREAD

**Issue by Unperknown** [Junyeong-Market/Eliverd-API#46]
오늘 애플리케이션 개발을 재개하는 중에 `POST /account/session` 요청으로 400 에러가 나고 있습니다. 확인 결과 DB에 유저 정보는 저장되어 있고 내부 로직 오류인 것으로 추정됩니다. 애플리케이션 대부분의 기능이 인증이 되어야만 동작하므로 조속히 확인해주셨으면 좋겠습니다.

**Comment by startergate** [comment]
에러가 재현되지 않습니다. request로 뭐가 날아가는지 관련 정보를 여기에 적어주세요.

**Comment by startergate** [comment]
request가 https로 전송되어 발생하는 에러로 보입니다.

**Comment by startergate** [comment]
장고 개발용 서버가 https를 지원하지 않아서 ssl을 할 생각은 없었는데 필요하다면 방법을 찾아서 해볼 수는 있어요 :)

**Comment by startergate** [comment]
#47 에서 서버 실행 환경을 변경해서 해결할 예정입니다. 그 전까지는 http를 사용해주세요
