### ISSUE TITLE
재고 폐기

### ISSUE THREAD

**Issue by startergate** [Junyeong-Market/Eliverd-API#8]

**Comment by Unperknown** [comment]
재고 폐기 기능을 수행하는 로직이 아직 확실히 정해지지 않은 것 같아서 코멘트 남깁니다.

현재까지 `POST /store/:storeId/stock` 엔드포인트에서 재고 폐기를 함께 처리하는 것으로 되어 있는데 이 이슈에서 로직이 완전히 구성될 수 있도록 자세히 이야기하는 것이 좋을 것 같습니다!

@startergate

**Comment by startergate** [comment]
#14 에서 묶어서 처리
